# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:

env: 
  JP2: ${{ secrets.JP2 }}

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies 
        run: |
          python3 -m pip install flake8 pytest

      - name: Pytest
        run: |
          pytest
        
      
      
     
